"""Quantise a trained policy network to int8 and export it for the microcontroller (roadmap stage 2).

Each weight matrix gets one symmetric int8 scale (w ~ q * scale, q in -127..127);
biases stay float32. Writes

* <out>.npz  - the dequantised network in the usual format, to evaluate the
               accuracy loss with compare_gpu.py / compare.py,
* <out>.h    - a C header with the int8 weights, their scales, float biases and
               the layer sizes, for inference on the UNO Q's MCU.

    python scripts/quantize_policy.py runs/harsh_hist.npz --out runs/harsh_hist_int8
"""
from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from flute_rl.policy import load_net  # noqa: E402

NAMES = {"mlp": ["w1", "b1", "w2", "b2"], "gru": ["W", "U", "b", "Wo", "bo"]}


def split(net) -> dict[str, np.ndarray]:
    flat, parts, i = net.get_flat(), {}, 0
    for name, s in zip(NAMES[net.arch], net.shapes):
        n = int(np.prod(s))
        parts[name] = flat[i:i + n].reshape(s)
        i += n
    return parts


def c_array(ctype: str, name: str, values: np.ndarray, per_line: int = 16) -> str:
    vals = [str(int(v)) if ctype == "int8_t" else f"{float(v):.8g}f" for v in values.ravel()]
    lines = [", ".join(vals[k:k + per_line]) for k in range(0, len(vals), per_line)]
    return f"static const {ctype} {name}[{len(vals)}] = {{\n  " + ",\n  ".join(lines) + "\n};\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("net")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    net, meta = load_net(args.net)
    parts = split(net)
    deq, header = {}, []
    prefix = pathlib.Path(args.out).name.upper().replace("-", "_")
    header.append(f"// {pathlib.Path(args.net).name}: {net.arch.upper()} in {net.in_dim}, hidden {net.hidden}, out {net.out_dim}\n")
    header.append(f"// int8 weights with one scale per matrix (w = q * scale); float biases. Generated by quantize_policy.py\n")
    header.append("#pragma once\n#include <stdint.h>\n\n")
    header.append(f"#define {prefix}_IN {net.in_dim}\n#define {prefix}_HIDDEN {net.hidden}\n#define {prefix}_OUT {net.out_dim}\n\n")
    bytes_total, err = 0, []
    for name, w in parts.items():
        if w.ndim == 2:
            scale = float(np.max(np.abs(w)) / 127.0) or 1.0
            q = np.clip(np.round(w / scale), -127, 127).astype(np.int8)
            deq[name] = q.astype(float) * scale
            err.append(float(np.max(np.abs(deq[name] - w))))
            header.append(f"static const float {prefix}_{name.upper()}_SCALE = {scale:.8g}f;\n")
            header.append(c_array("int8_t", f"{prefix}_{name.upper()}", q.T))  # stored output-major for dot products
            bytes_total += q.size + 4
        else:
            deq[name] = w
            header.append(c_array("float", f"{prefix}_{name.upper()}", w.astype(np.float32)))
            bytes_total += 4 * w.size
    net.set_flat(np.concatenate([deq[n].ravel() for n in NAMES[net.arch]]))
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    net.save(out.with_suffix(".npz"), **meta)
    out.with_suffix(".h").write_text("".join(header), encoding="utf-8")
    print(f"{net.n_params} parameters -> {bytes_total} bytes on the MCU (float32 would be {4 * net.n_params}); "
          f"largest weight change {max(err):.2e}")
    print(f"wrote {out.with_suffix('.npz')} and {out.with_suffix('.h')}")


if __name__ == "__main__":
    main()
