"""Train the separated feedback residual with causal DAgger rollouts.

Unlike the old pseudo-autoregressive BC, every next self-audio frame here is
generated by the action the current network actually applied to the plant.
The Oracle is queried only for a supervised label at that visited state.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np
import torch
from torch.nn import functional as F

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from flute_rl.audio import room, synth_source  # noqa: E402
from flute_rl.targets import make_target, sample_level  # noqa: E402
from flute_rl.yamabiko import Oracle, Rig, RigParams, make_schedule  # noqa: E402
from flute_rl.yamabiko.e2e import E2EImitator  # noqa: E402
from flute_rl.yamabiko.e2e_audio import RawSelfAudio  # noqa: E402
from flute_rl.yamabiko.e2e_io import SAMPLE_RATE, frame_audio_numpy  # noqa: E402
from flute_rl.yamabiko.staged_nn import (ErrorComparator, FeedForwardPolicy,
                                         FeedbackResidualPolicy, ReferenceMemory,
                                         StagedConfig)  # noqa: E402


def load(path, device):
    ck = torch.load(path, map_location=device); cfg = StagedConfig(**ck["config"])
    memory, ff, comparator, feedback = ReferenceMemory(cfg), FeedForwardPolicy(cfg), ErrorComparator(cfg), FeedbackResidualPolicy(cfg)
    for module, key in zip((memory, ff, comparator, feedback), ("memory", "feedforward", "comparator", "feedback")):
        module.load_state_dict(ck[key]); module.to(device)
    ear = E2EImitator.from_checkpoint(torch.load(ck["ear_checkpoint"], map_location=device), device).eval()
    memory.eval(); ff.eval(); comparator.eval()
    for module in (ear, memory, ff, comparator):
        for p in module.parameters(): p.requires_grad_(False)
    return ck, ear, memory, ff, comparator, feedback


@torch.inference_mode()
def reference_features(target, rng, ear, memory, ff, batch, device):
    wave, _ = synth_source(target, "recorder", rng, sr=SAMPLE_RATE)
    frames = frame_audio_numpy(room(wave, SAMPLE_RATE, rng), len(target))
    learned = ear.audio_features(torch.from_numpy(frames).to(device))[:, -2:]
    length = torch.tensor([len(target)], device=device)
    _, stored = memory(learned[None], length); decoded = memory.decode(stored)
    base = ff(decoded, length)
    return decoded.expand(batch, -1, -1).contiguous(), base.expand(batch, -1, -1).contiguous()


@torch.inference_mode()
def collect(target_np, decoded, base, rng, ear, comparator, feedback, device, harsh):
    batch, steps = decoded.shape[:2]
    params = RigParams.sample(rng, batch, harsh=harsh)
    rig = Rig(params, np.random.default_rng(int(rng.integers(2**31))))
    schedule = make_schedule([[target_np for _ in range(batch)]])
    oracle = Oracle(); oracle.begin(schedule, rig)
    for t in range(100):
        pwm = -np.ones(batch); out = rig.step(pwm, np.zeros(batch, bool)); oracle.update(t, pwm, out)
    oracle.homed()
    audio = RawSelfAudio(batch, rng, domain=1.0)
    state = torch.zeros(batch, feedback.config.control_hidden, device=device)
    previous = torch.zeros(batch, 2, device=device)
    own_seq, error_seq, labels = [], [], []
    for t in range(steps):
        own = ear.audio_features(torch.from_numpy(audio.buf.copy()).to(device))[:, -2:]
        estimated = comparator(decoded[:, t], own)
        action, state = feedback.step(decoded[:, t], own, estimated, base[:, t], previous, state)
        label = np.asarray(oracle.act(100 + t), np.float32)
        action_np = action.cpu().numpy(); out = rig.step(action_np[:, 0], action_np[:, 1] >= .5)
        oracle.update(100 + t, action_np[:, 0], out); audio.push(out["cents"], out["sounding"])
        own_seq.append(own.cpu()); error_seq.append(estimated.cpu()); labels.append(torch.from_numpy(label))
        previous = action
    return torch.stack(own_seq, 1).to(device), torch.stack(error_seq, 1).to(device), torch.stack(labels, 1).to(device)


def train_sequence(feedback, optimizer, decoded, base, own, error, labels):
    batch, steps = decoded.shape[:2]
    state = torch.zeros(batch, feedback.config.control_hidden, device=decoded.device)
    previous = torch.zeros(batch, 2, device=decoded.device)
    predicted = []
    for t in range(steps):
        action, state = feedback.step(decoded[:, t], own[:, t], error[:, t], base[:, t], previous, state)
        predicted.append(action[:, 0]); previous = action
    predicted = torch.stack(predicted, 1)
    loss = F.smooth_l1_loss(predicted, labels)
    optimizer.zero_grad(set_to_none=True); loss.backward(); torch.nn.utils.clip_grad_norm_(feedback.parameters(), 1); optimizer.step()
    return float(loss.detach())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--init", default="runs/yamabiko_staged_nn.pt"); ap.add_argument("--out", default="runs/yamabiko_staged_nn_feedback.pt")
    ap.add_argument("--report", default="runs/yamabiko_feedback_train_report.json")
    ap.add_argument("--iterations", type=int, default=300); ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--lr", type=float, default=5e-4); ap.add_argument("--harsh", type=float, default=.4)
    ap.add_argument("--seed", type=int, default=8128); ap.add_argument("--progress", type=float, default=.8)
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = ap.parse_args(); rng = np.random.default_rng(args.seed); torch.manual_seed(args.seed)
    ck, ear, memory, ff, comparator, feedback = load(args.init, args.device); feedback.train()
    optimizer = torch.optim.AdamW(feedback.parameters(), lr=args.lr, weight_decay=1e-6)
    losses = []
    for iteration in range(1, args.iterations + 1):
        target = make_target(rng, sample_level(rng, args.progress))
        decoded, base = reference_features(target, rng, ear, memory, ff, args.batch, args.device)
        own, error, labels = collect(target, decoded, base, rng, ear, comparator, feedback.eval(), args.device, args.harsh)
        value = train_sequence(feedback.train(), optimizer, decoded, base, own, error, labels); losses.append(value)
        if iteration == 1 or iteration % 20 == 0: print(f"iteration {iteration:4d} dagger loss {value:.5f}", flush=True)
    ck["feedback"] = feedback.eval().state_dict(); ck["feedback_training"] = {
        "method": "causal DAgger", "iterations": args.iterations, "batch": args.batch,
        "harsh": args.harsh, "seed": args.seed, "final_loss": losses[-1], "mean_last_20": float(np.mean(losses[-20:]))}
    torch.save(ck, args.out); pathlib.Path(args.report).write_text(json.dumps(ck["feedback_training"], indent=2), encoding="utf-8")
    print(json.dumps(ck["feedback_training"], indent=2)); print(f"saved {args.out}")


if __name__ == "__main__": main()
